---
mainfont: Times New Roman
brand:
  typography:
    headings:
      family: Times New Roman
format:
  faru-termpaper-typst: default
filters: [include-code-files]
margin:
  left: 25mm
  right: 10mm
  top: 20mm
  bottom: 20mm
  x: auto
  y: auto
fontsize: 14pt
papersize: a4
paragraph:
  indent: 2.5em
section-numbering: 1.1.1
toc-indent: 0em
page:
  numbering:
    type: '1'
    align: bottom + center
    start: 3
