# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "exp-workflow" ]
  pull_request:
    branches: [ "exp-workflow" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: application
        path: target/chat-*.jar
  render:
    runs-on: ghcr.io/quarto-dev/quarto:1.7.19

    steps:
    - uses: actions/checkout@v4
    - name: Render with Quarto
      uses: quarto-dev/quarto-actions/render@v2
      env:
        TYPST_FONT_PATHS: ./
      with:
        path: doc/report/
    - name: Archive Report Artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: ../../doc/report/java-rep.pdf
  publish:
    runs-on: ubuntu-latest
    needs: [build, render]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Application Artifact
        uses: actions/download-artifact@master
        with:
          name: application
      - name: Download Application Artifact
        uses: actions/download-artifact@master
        with:
          name: application
      - name: Download Application Artifact
        uses: actions/download-artifact@master
        with:
          name: report
      - name: Upload the built app and report
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '{chat-*,java-rep.pdf}'

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
 #   - name: Update dependency graph
 #     uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
